<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.bank</groupId>
    <artifactId>bank-backend</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Enterprise Digital Bank Backend</name>
    <description>Production Grade Banking Platform</description>

    <modules>
        <module>platform/discovery-server</module>
        <module>platform/config-server</module>
        <module>platform/api-gateway</module>

        <module>services/auth-service</module>
        <module>services/customer-service</module>
        <module>services/account-service</module>
        <module>services/transaction-service</module>
        <module>services/beneficiary-service</module>
        <module>services/branch-service</module>
        <module>services/loan-service</module>
        <module>services/card-service</module>
        <module>services/notification-service</module>
        <module>services/fraud-service</module>
        <module>services/audit-service</module>

        <module>shared/common-lib</module>
        <module>shared/security-lib</module>
        <module>shared/observability-lib</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring.boot.version>3.5.0</spring.boot.version>
        <spring.cloud.version>2025.0.0</spring.cloud.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.14.0</version>
                    <configuration>
                        <source>21</source>
                        <target>21</target>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring.boot.version}</version>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

</project>